FORMAT: 1A
HOST: https://trade-hk.osl.com/

# OSL Digital Securities (OSLDS) Exchange API v3 Documentation

The OSL Digital Securities (OSLDS) Exchange API v3 provides a clean JSON exchange interface for OSL Digital Securities exchange users.

Note: The base URL referred in this document (https://bct.host) is provided by the whitelabel operator. For example, https://trade-hk.osl.com is the base URL for the OSL Digital Securities (OSLDS) Exchange operator.

## Group Quickstart Catalog

### Authentication
* [API Key Creation](#reference/authentication/apikey) - Obtaining an API Key
* [Obtaining a Push Data Token](#reference/authentication/datatoken) - Obtaining a token to access push data services

### Account
* [Account](#reference/account/account) - Create account info of the API key owner
* [Sub Account](#reference/account/subaccountnew) - Create a sub account for a specified crypto currency

### Activity
* [Transaction List](#reference/activities/transactionlist) - list transactions of the API key owner

### Funding
* [Send](#reference/funds/send) - Send fund currencies
* [Receive](#reference/funds/receive) - Obtain an address for receiving funds
* [Receive Create](#reference/funds/receivecreate) - Create a new crypto address for receiving funds


### Order
* [Create/Replace Order](#reference/order/ordernew) - Create/place an order 
* [Order Status](#reference/order/orderinfo) - Order status and detail of an order
* [Order Status By OrderId](#reference/order/{orderId}) - Order status and detail of an order

### Streaming 
* [Public Events](#reference/streaming) - Public event like market tick, order, order book,
* [Private Events](#reference/streaming) - Account, Order status, Trade status, and user activities

## Group Quick Start
### Getting an API Key
In order to use the API, you must obtain an API key and secret. 

This can be done through the web site, or via the API.

####Via the Web
For you to do this, login to https://bct.host, and navigate to the Settings page from the top-right menu icon.  You will see the 'API' tab there and please click on it. 

If you try to create the API and secret for the first time, click 'Create' button on the API Keys page to generate a new API key pair.  If you have enabled two-factor security, you will need to enter a one-time-password (OTP) now.  Please copy down the API key and the secret to a safe place for future usage.  Note that the website will only show the API secret afterward.

If you forget/lost the API secret, you can click the 'Reset Secret' button to re-generate a new API secret.  Please note that old API secrets will be disabled automatically once the secret got reset.  All old secrets cannot be used with the API server.

You can enable the API key to allows/disable move funds and place orders.

If a single API key/secret is not enough for your usage, you can create multiple api key/secret if needed for different applications.

####Via the API

You can generate api key/secret pair using the [/api/3/apiKey](#reference/authentication/apikey) service.

You will need your username, password, and one-time-password (OTP) if two-factor security is enabled.

Note that api key/secret generated by the [/api/3/apiKey](#reference/authentication/apikey) service cannot place order by default.   You can change this settings via the Web. 


### Authenticate using Rest-Key and Rest-Sign
The API key and secret can be used to authenticate with BCG servers. This is achieved via the adding two HTTP headers: Rest-Key and Rest-Sign to each API call.

Rest-Key is your API key.

Rest-Sign is an HMAC hash constructed from your API secret, your API method path, your post data, and uses the SHA-512 algorithm.

* Note that api method path follow the pattern of "api/3/methodName/subMethodName". This is different from v2, which api method path is in the pattern of "methodName/subMethodName"

To test your Rest-Signs, use the following pseudocode:

```java
function hmac_512(msg, sec) {
    sec = Base64Decode(sec);
    result = hmac(msg, sec, sha512);
    return Base64Encode(result);
}

secret = "7pgj8Dm6";
message = "Test\0Message";

result = hmac_512(message, secret);
if (result == "69H45OZkKcmR9LOszbajUUPGkGT8IqasGPAWqW/1stGC2Mex2qhIB6aDbuoy7eGfMsaZiU8Y0lO3mQxlsWNPrw==")
    print("Success!");
else
    printf("Error: %s", result);
```    

#### Java / Groovy
```java

String sign(String base64Key, byte[] bytes) {
    Mac mac = Mac.getInstance("HmacSHA512");
    SecretKey secretKey = new SecretKeySpec(Base64.decode(base64Key.getBytes()), "HmacSHA512");
    mac.init(secretKey);
    mac.update(bytes);
    return Base64.encodeBytes(mac.doFinal()).trim();
}

def tonce = (new Date()).time*1000    
def postBody['tonce'] = tonce;
// put other parameters in postBody

String postBodyInJson = new Gson().toJson(postBody)
String path = 'api/3/receive'
String data = path + "\0" + postBodyInJson
String sign = sign(secret, data.getBytes())

```
#### Python

```python

import base64, hashlib, hmac, urllib2, time, urllib, json
base = 'https://bct.host/'


def post_request(key, secret, path, data):
    hmac_obj = hmac.new(secret, path + chr(0) + data, hashlib.sha512)
    hmac_sign = base64.b64encode(hmac_obj.digest())

    header = {
        'Content-Type': 'application/json',
        'User-Agent': 'bctv2 based client',
        'Rest-Key': key,
        'Rest-Sign': hmac_sign,
    }

    proxy = urllib2.ProxyHandler({'http': '127.0.0.1:8888'})
    opener = urllib2.build_opener(proxy)
    urllib2.install_opener(opener)

    request = urllib2.Request(base + path, data, header)
    response = urllib2.urlopen(request, data)
    return json.load(response)


def gen_tonce():
    return str(int(time.time() * 1e6))


class BCT:

    def __init__(self, key, secret):
        self.key = key
        self.secret = base64.b64decode(secret)

    def request(self, path, params={}):
        params = dict(params)
        params['tonce'] = gen_tonce()
        # data = urllib.urlencode(params)
        data = json.dumps(params)

        result = post_request(self.key, self.secret, path, data)
        if result['result'] == 'success':
            return result['data']
        else:
            raise Exception(result['result'])

x = BCT('<key>', '<secret>')
result = x.request('api/3/order/list')

```

#### CS
```cs
        string key = "";
        string secret = ""; 
        string path = "api/3/order/list";

        long unixTimestamp = (long)(DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1))).TotalSeconds;
        long ts = unixTimestamp * 1000 * 1000;

        string command = "{\"nonce\":"+ts+",\"max\":\"100\"}";

        HMACSHA512 hmacsha512 = new HMACSHA512(Convert.FromBase64String(secret));
        string input= path + '\0' + command;
        MemoryStream stream = new MemoryStream(Encoding.ASCII.GetBytes(input));
        byte[] hashData = hmacsha512.ComputeHash(stream);
        string sign = Convert.ToBase64String(hashData);

        var request = System.Net.WebRequest.Create("https://bct.host/" + path) as System.Net.HttpWebRequest;

        request.KeepAlive = true;
        request.Method = "POST";

        request.ContentType = "application/json";
        request.Headers.Add("rest-key", key );
        request.Headers.Add("rest-sign", sign);


        byte[] byteArray = System.Text.Encoding.UTF8.GetBytes(command);
        using (var writer = request.GetRequestStream()){writer.Write(byteArray, 0, byteArray.Length);}

        string responseContent=null;
        using (var response = request.GetResponse() as System.Net.HttpWebResponse) {
            using (var reader = new System.IO.StreamReader(response.GetResponseStream())) {
                responseContent = reader.ReadToEnd();
                Console.WriteLine(responseContent);
            }
        }

```
#### PHP
```php
$key = '';
$secret = '';

$param['max'] = 100;
$param['tonce'] = time() * 1000 * 1000;

// generate the POST data string
$post_data = json_encode($param);

$prefix = $path ."\0";

// generate the extra headers
$headers = array(
    'Rest-Key: '.$key,
    'Rest-Sign: '.base64_encode(hash_hmac('sha512', $prefix.$post_data, base64_decode($secret), true)),
    'Content-Type: application/json'
);

```

## Group Supported currency and currency pair


## GET /currencyStatic
### Obtain supported currency and currency pair
This endpoint returns a list of supported currencies and currency pairs of the platform.

No Rest-Key and Rest-Sign in HTTP Header.

### e.g bct.host supported fiats
```java
USD, HKD, EUR, CAD, AUD, SGD, JPY, GBP, NZD
```
###  e.g. bct.host supported crypto currencies
```java
BTC, LTC, DOGE, STR, XRP
```
### e.g bct.host supported currency pairs
```java
BTCUSD,BTCHKD,BTCEUR,BTCCAD,BTCAUD,BTCSGD,BTCJPY,BTCGBP,BTCNZD,
LTCBTC,DOGEBTC,STRBTC,XRPBTC
```

##### Request Definition

| Fields        | Description| Example |
| ------------- |-------------|---------

##### Response Definition

| Fields        | Description|  Example
| ------------- |-------------| ---------
| timestamp   | UNIX timestamp in milliseconds |
| resultCode   | Result code reflecting the success status of the operation. |
| currencyStatic | see Currency Static |


##### Currency Static

| Fields        | Description|  Example
| ------------- |-------------| ---------
| currencies   | map of ccy and currency settings | e.g. BTC
| currencyPairs   | map of CcyPair and Currency Pair Settings | e.g BTCUSD

##### Currency Settings

| Fields        | Description|  Example
| ------------- |-------------| ---------
| decimals |  decimal place used for trading
| minOrderSize | minimum order size
| maxOrderSize | maximum order size
| minOrderValue| minimum order value
  maxOrderValue| minimum order value
| maxMarketOrderValue| maximum market order value
| maxMarketOrderSize| maximum market order size
| displayDenominator | display denominator | 1000
| summaryDecimals |   decimals place used to display summary | e.g. 0 
| display Unit | currency unit | e.g. kDOGE
| symbol | symbol of the currency | e.g. Ɖ for DODGE
| type | CRYPTO or FIAT |
| confirmationThresholds |
| networkFee| standard network fee | 0.00010000
| engineSettings | see Fund Engine Settings
| urlPrefix| url prefix to handle the relatd coin address | bitcoin:
| digitalCurrencyType | SATOSHI, COLORED_COIN_OPEN_ASSETS, MULTICHAIN, MULTICHAIN_NATIVE, RIPPLE, RIPPLE_IOU, ETHEREUM, ETHEREUM_TOKEN | 
| assetId | (CRYPTO type only) | e.g.
| assetName | (CRYPTO type only) | e.g. BCT
| assetDivisibility | (CRYPTO type only) asset divisibility | e.g. 2
| assetIcon | (CRYPTO type only) asset icon | 
| assetIssueQuantity| (CRYPTO type only) asset issue quantity |e.g. 10000

##### Fund Engine Settings

| Fields        | Description|  Example
| ------------- |-------------| ---------
| depositsEnabled | true if deposits enabled
| withdrawalsEnabled  | true if  withdrawals enabled
| displayEnabled | true if  display enabled. The app should hide the currency to respect the platform 
| mobileAccessEnabled | true always from API v3

##### Currency Pair Settings

| Fields        | Description|  Example
| ------------- |-------------| ---------
| priceDecimals | decimals place of price for trading
| engineSettings  | see Order Engine Settings
| minOrderRate | minmium order rate
| maxOrderRate | maxmium order rate
| displayPriceDecimals | decimals place of price for display
| tradedCcy | traded Ccy |  e.g BTC for BTCUSD
| settlementCcy | settlement Ccy | e.g USD for BTCUSD
| preferredMarket | BCT, BITFINEX, BTCE, EGDMARKET, RIPPLE

##### Order Engine Settings

| Fields        | Description|  Example
| ------------- |-------------| ---------
| tradingEnabled | true if trading enabled 
| displayEnabled | true if display enabled 
| cancelOnly | cancel 
| verifyRequired | true if verification required for trading
| restrictedBuy | true if user cannot buy the currency pair
| restrictedSell | true if user cannot sell the currency pair

+ Request (application/json)
        
    + Body
        
            {
            }

+ Response 200 (application/json)

    + Body
    
            {
            }


# Group Authentication 

## POST /apiKey
### Obtain an API Key
This service creates a new API Key, or resets the secret key on an existing API Key.

Unlike other requests, this request is not signed with an API key, rather the user's credentials are posted in the request.

##### Request Definition

| Fields        | Description| Example |
| ------------- |-------------|---------
| nonce         | Ever increasing integer |
| username        | email address of the registered account |
| password  | password of the registered account |
| otp      | otp key if the user has OTP enabled |
| allowMoveFund | true if the api key allow to move fund |
| deviceId    | unique identifying string for the calling client/ device. Note that subsequent calls with the same deviceId will reset the secret key - so this cannot be shared across multiple devices. |

##### Response Definition

| Fields        | Description|  Example
| ------------- |-------------| ---------
| timestamp   | UNIX timestamp in milliseconds |
| resultCode   | Result code reflecting the success status of the operation. |
| apiKey       | Identifier for the api key, which identifies the user |
| apiSecret        | Secret key for the api key which is used to sign requests. This must be secured as it can be used to compromise the user's account |

+ Request (application/json)

    + Headers
        
            Rest-Key: <Your-Rest-Key>
            Rest-Sign: <Your-Rest-Sign>
            
    + Body
        
            {
                "nonce":"1393225933584",
                "username":"username@yourdomain.com",
                "password":"yourpassword",
                "otp":"123312",
                "deviceId":"name and unique id of device",
                "allowMoveFund": true
            }

+ Response 200 (application/json)

    + Body
    
            {
                "apiKey":"e218acc3-7907-47b8-879c-302f0c1904bc",
                "apiSecret":"WcqucbLH7fNDK6LeQXI+Ian5cvhVC3kYOUD/Q8mWaEW3CMsjEeBgCA3qBZKF6YckwTkb04OA1nNuoJFqsffr+Q==",
                "resultCode":"OK",
                "timestamp":1393319666969
            }

## POST /apiKey/create

### only available to Master API Key
Create or update a api key for user. Only allow if the authorized api key is the master API key.  

* Whitelabel client can set site owner's api key as the "Master" API key
* If you are site owner of one of our whitelabel clients, you can request this feature from BCG.

##### Request Definition
| Fields        | Description| Example
| ------------- |-------------|---------
| nonce         | Ever increasing integer |
| userUuid      | user's uuid | 41da01ac-e011-4a20-b3af-37ee05a885e
| deviceId      | name of api key | e.g. apiKey1
| allowMoveFund | true if user can withdraw fiat or crypto |
| placeOrders   | true if user can trade | 

##### Response Definition

| Fields        | Description|  Example
| ------------- |-------------| ---------
| timestamp   | UNIX timestamp in milliseconds |
| resultCode  | Result code reflecting the success status of the operation. |
| userUuid    | user's uuid return by autoRegister | 41da01ac-e011-4a20-b3af-37ee05a885e
| apiKey      | Identifier for the api key, which identifies the user |
| apiSecret   | Secret key for the api key which is used to sign requests. This must be secured as it can be used to compromise the user's account |


+ Response 200 (application/json)

        {
            "nonce":"1468377906313",
            "userUuid":"6b2038d1-7e2a-446f-b8a0-0be00c44ca66",
            "deviceId":"testbyme3",
            "allowMoveFund":true,
            "placeOrders":true
        }

## POST /dataToken
### Obtain an data token for access to data push services
Use this service to obtain a data token and uuid for access to data push services. Firebase is currently supported.

The token expires after 24 hours - client software should regularly check the validity of it's token, and use this service to obtain a fresh one when required.

##### Request Definition

| Fields        | Description| Example |
| ------------- |-------------|---------
| nonce         | Ever increasing integer | 

##### Response Definition

| Fields        | Description|  Example
| ------------- |-------------| ---------
| timestamp   | UNIX timestamp in milliseconds |
| resultCode   | Result code reflecting the success status of the operation. |
| token      | data token  | |
| uuid        | user's uuid  | |

+ Request (application/json)

    + Headers
    
            Rest-Key: <Your-Rest-Key>
            Rest-Sign: <Your-Rest-Sign>
        
    + Body
    
            {
                "nonce":"1393225933584"
            }

+ Response 200 (application/json)

    + Body
    
            {
                "resultCode":"OK",
                "timestamp":1393319875875,
                "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2IjowLCJkIjp7ImFub255bW91cyI6ZmFsc2UsInV1aWQiOiJjNDMxNzBhYy05YWRkLTExZTMtODBiZS1hYzIyMGI4Mzk3MDkifSwiaWF0IjoxMzkzMzE5ODc1fQ.caxseibxgQXItwjLeSCaflYwrqlx444GbvOlIm6pjJo",
                "uuid":"739e032d-9e9d-11e3-b33a-ac220b839709"
            }
            
# Group Registration

## POST /register/register

### Register an user account

The platform will send email with verification code if user registered correctly.

##### Request Definition
| Fields        | Description| Example
| ------------- |-------------|---------
| nonce         | Ever increasing integer |
| username | user account name | user's email
| userTimezone |  Timezone of user's registration country | Hong Kong
| country | Three letter country code| chn
| accepttc | true to accept t&c of the platform. Must set to true to register successfully| true
| language |User preferred language | en_US
| isMobile | true if called is from mobile | default is true  
    
##### Response Definition

| Fields        | Description|  Example
| ------------- |-------------| ---------
| timestamp   | UNIX timestamp in milliseconds |
| resultCode   | OK | OK if register successfully

+ Response 200 (application/json)

    + Body
    
            {
                "resultCode":"OK"
            }
            
## POST /register/verifyRegistration

### Verify registration

No Rest-Key and Rest-Sign in HTTP header.

The platform will send email with verification code for user to complete registration.

##### Request Definition
| Fields        | Description| Example
| ------------- |-------------|---------
| nonce         | Ever increasing integer |
| verificationCode | verification code | 
| password |  password  |
| password2 | password2 needs to match password |
| accepttc | true to accept t&c of the platform. Must set to true to register successfully| true
| country |Three letter country code| chn
    
##### Response Definition

| Fields        | Description|  Example
| ------------- |-------------| ---------
| timestamp   | UNIX timestamp in milliseconds |
| resultCode   | OK if verification succeed. SYSTEM_ERROR if verification fail

+ Response 200 (application/json)

    + Body
    
            {
                "resultCode":"OK"
            }
            
## POST /register/resendVerification

### Resend verification

The platform resend verification email to the user.

No Rest-Key and Rest-Sign in HTTP header.

##### Request Definition
| Fields        | Description| Example
| ------------- |-------------|---------
| username         | email for verification code to be resend |
| isMobile | true if called is from mobile | default is true  
    
##### Response Definition

| Fields        | Description|  Example
| ------------- |-------------| ---------
| timestamp   | UNIX timestamp in milliseconds |
| resultCode   | OK if verification succeed

+ Response 200 (application/json)

    + Body
    
            {
                "resultCode":"OK"
            }

## POST /register/autoRegister
Create an user account without email confirmation.  This account cannot be login from website/mobile app. 
The account is only accessible by the master key api.
* Whitelabel client can set site owner's api key as the "Master" API key
* If you are site owner of one of our whitelabel clients, you can request this feature from BCG.


##### Request Definition
| Fields        | Description| Example
| ------------- |-------------|---------
| nonce         | Ever increasing integer |
| userTimezone  | Timezone of user's registration country | Hong Kong
| country       | Three letter country code| hkg
| accepttc      |  true to accept t&c of the platform.  Must set to true to register successfully | true
| language      | User preferred language | en
| usernameType  | Type of user account name | PHONENUMBER
| username      | user account name | +85295271816

##### User Name Type

| Fields        | Description| Example
| ------------- |-------------|---------
| PHONENUMBER   | use phone number as username
| EMAIL   | use email as username
| UUID   | use UUID  as username

##### Langauge

| Fields        | Description
| ------------- |-------------|
| en
| en_US
| zh_CN
| zh_HK
| pt_BR
| ja
| ja_JP


##### Response Definition

| Fields        | Description|  Example
| ------------- |-------------| ---------
| timestamp   | UNIX timestamp in milliseconds |
| resultCode   | Result code reflecting the success status of the operation. |
| userUuid | user's uuid
| username      | user's username  | |

+ Response 200 (application/json)

        {
            "username": "6b2038d1-7e2a-446f-b8a0-0be00c44ca66",
            "timestamp": "1234123412412342134",
            "resultCode":"OK",
            "userUuid": "6b2038d1-7e2a-446f-c8a0-0be00c77ca66"
        }

# Group Account

## POST /account
### Get account information
The platform has 3 unique accounts for each user. 
- `Available_Balance` is updated with deposits, withdrawals and retail trades (if supported by the platform). 
- `Exchange_Available_Balance` is the balance available to be traded on the exchange (if supported by the platform). Funds must be moved from `Available_Balance`. 
- `Balance` is the sum of `Available_Balance` & `Exchange_Available_Balance`.

If userUuid is being specified in request, the client can get the user account information if the API key is master API key
* Whitelabel client can set site owner's api key as the "Master" API key
* If you are site owner of one of our whitelabel clients, you can request this feature from BCG.

##### Request Definition
| Fields        | Description| Example |
| ------------- |-------------|---------
| nonce         | Ever increasing integer | 
| userUuid      | (for master api key only) user's uuid |

##### Response Definition

| Fields        | Description|  Example
| ------------- |-------------| ---------
| timestamp   | UNIX timestamp in milliseconds |
| resultCode   | Result code reflecting the success status of the operation. |
| data      | info result  | See Info Result |
| userUuid        | user's uuid  | |

Info Result

| Fields        | Description|  Example
| ------------- |-------------| ---------
| Created      | created date in format (yyyy-MM-dd HH:mm:ss)  |  |
| Language        | user's prefered language  | e.g. en_US |
| Login   | username | |
| Trade_Fee | ordering fee | |
| Rights | list of access right | ["trade", "withdraw", "get_info" ] |
| Wallets | map of ccy and wallet | See Wallet |

Wallet
| Fields        | Description|  Example
| ------------- |-------------| ---------
| Balance      | Sum of Available balance + Exchange Available balance (Amount) |  |
| Available_Balance        | Primary account's available balance (Amount) |
| Primary_Available_Balance        | primary available balance(Amount) |
| Exchange_Available_Balance        | Exchange account's available balance (Amount) |

Amount
| Fields        | Description|  Example
| ------------- |-------------| ---------
| displayShort  | Display in short | 199.99 BTC |
| valueInt      | Value in Integer | 19999400000 | 
| currency      | currency  | BTC | 
| display       | display in full | 199.99400000 BTC |
| value         | value | 199.99400000 |

+ Response 200 (application/json)

## POST /subaccount/new
### Create a new sub-account to receive crypto funds for the given token
Use this endpoint to create a new sub-account. There will be a new crypto address tied to this sub-account to recieve crypto funds.

##### Request Definition

| Fields        | Description| Example
| ------------- |-------------|---------
| nonce         | Ever increasing integer |
| ccy         | traded currency (currently one of BTC, LTC, DOGE, XRP and STR) |
| customRef | an alias of this subaccount, like "Entertainment Funds" (NOTE: please do not name your subaccount as "DEFAULT" or "default", these two key words are reserved.) |

##### Response Definition

| Fields        | Description|  Example
| ------------- |-------------| ---------
| resultCode   | Result code reflecting the success status of the operation. | OK
| timestamp   | UNIX timestamp in milliseconds |
| subAccount  | UUID of the subAccount newly created.  |


+ Request (application/json)

    + Headers
    
            Rest-Key: <Your-Rest-Key>
            Rest-Sign: <Your-Rest-Sign>
        
    + Body
    
            {
                "nonce":"1393225933579",
                "ccy":"DOGE",
                "customRef":"Entertainment Funds"
            }

+ Response 200 (application/json)

    + Body
        
            {
               "resultCode": "OK",
               "timestamp": 1401332162768,
               "subAccount": "672ee29e-0a8b-4fce-b9d5-97b9cf278742"
            }



# Group Activities
## POST /transaction/list
By querying this endpoint, you can get your transactions (max result: 200). You can specify date range and/or offset so that you can paginate the transactions returned.

##### Request Definition
| Fields        | Description| Example
| ------------- |-------------|---------
| nonce         | Ever increasing integer | 
| ccy           | currency | BTC (optional)
| transactionState        | TransactionState   | e.g.PROCESSED (optional)
| from          | start time(inclusive) of queries transaction, format should be a number (UNIX timestamp in milliseconds) (optional)  | 1464675012000
| to            | end time(inclusive) of queries transaction, format is same as 'from' (optional)  | 1464679012000
| max           | Max results you want the endpoint to return. Note that it can be no greater than 200. Default value is 50 if not provided. (optional) | 50
| offset        | if there is more than 'max' results between the date range you specified, this field is useful for you to get the next 'max' results  (optional) | if max is 200, and there are actually 407 results in the date range, offset=400 will get you the last 7 results
| lang          | displayTitle and displayDescription for each transaction returned will be in the language specified. Default is "en-US". (optional)  | en-US


##### TransactionState

| Fields        | Description
| ------------- |-------------|---------
|SUBMITTED| Transaction submitted
|PROCESSED| Transaction has been processed
|SUSPENDED| Transaction has been suspended 
|REVERSED | Reversed 
|LIMIT_OVERRIDE_APPROVED | Limit overrided
|CANCELLED_INSUFFICIENT_FUNDS| Cancelled insufficent funds
|CANCELLED_LIMIT_BREACH | Cancelled - limit breach 
|PENDING_CONFIRM | Pending confirmation
|PENDING_SUFFICIENT_CONFIRMATIONS | Pending confirmation
|PENDING_REVERSE | Pending to reverese
|PENDING_LIMIT_APPROVAL | Pending limit approval

##### Language
| Fields        | Description
| ------------- |-------------|---------
| zh-CN | Simplified Chinese
| zh-HK | Traditional Chinese
| pt-BR | 
| en-US | English (US)
| ja-JP | Japanese 


##### Response Definition

| Fields        | Description|  Example
| ------------- |-------------| ---------
| resultCode   | Result code reflecting the success status of the operation. |
| timestamp   | UNIX timestamp in milliseconds |
| transactions        | list of transactions.  See Transaction  |
| count        | number of transactions returned  |

##### Transaction

| Fields        | Description|  Example
| ------------- |-------------| ---------
| transactionClas | FILL, COUPON and etc | 
| uuid| uuid of the transaction|  6d568392-ce9f-42b9-bfe6-074cffa78d6b
| userUuid | uuid belong to the user | 67271c1d -2f9b-48e2- a5bb-01c8a8ce11a4
| amount | total amount of the transaction| e.g -1.00345678
| fee | fee included in the transaction |  0.0
| balanceBefore| balance before the transaction |  105337.05233524
| balanceAfter | balance after the transaction |  105336.04887846,
| ccy | account currency | BTC
|transactionState | transaction state | e.g. PROCESSED
|transactionType | transaction tpe | FILL_DEBIT
|received | recieved timestamp | 1431004151000
|processed | processed timestamp | 1431004151000
|timestampMillis | created timestamp | 1464677126478
|displayTitle | Order Fill |
|displayDescription | Sell BTC @ 3231.23333 HKD / BTC or quoteId: xxxx-xxxx-xxxx-xxxxxxxxxxx|


+ Response 200 (application/json)

    + Body
    
            {
                "transactions": [{
                    "transactionClass": "FILL",
                    "uuid": "6d568392-ce9f-42b9-bfe6-074cffa78d6b",
                    "userUuid": "67271c1d -2f9b-48e2- a5bb-01c8a8ce11a4",
                    "amount": -1.00345678,
                    "fee": 0.0,
                    "balanceBefore": 105337.05233524,
                    "balanceAfter": 105336.04887846,
                    "ccy": "BTC",
                    "transactionState": "PROCESSED",
                    "transactionType": "FILL_DEBIT",
                    "received": 1431004151000,
                    "processed": 1431004151000,
                    "timestampMillis": 1464677126478,
                    "displayTitle": "Order Fill",
                    "displayDescription": "Sell BTC @ 3231.23333 HKD / BTC"
                },
                {
                      "transactionClass": "MERCHANT",
                      "uuid": "14e425ff-655a-4fc9-a837-98485c1ae529",
                      "userUuid": "aadf3778-8233-4c24-99ca-ca9144025ec6",
                      "amount": -0.99000000,
                      "fee": 0E-8,
                      "balanceBefore": 0.0,
                      "balanceAfter": 0.0,
                      "ccy": "USD",
                      "transactionState": "PROCESSED",
                      "transactionType": "TRADE_DEBIT",
                      "received": "1570775807000",
                      "processed": "1570775806656",
                      "timestampMillis": "1571276982260",
                      "displayTitle": "Currency Conversion",
                      "displayDescription": "quoteId: efa4b313-b84a-423c-8319-29133010ac3c",
                      "quoteId": "efa4b313-b84a-423c-8319-29133010ac3c",
                      "tradeId": "a2fb9700-9040-4886-9993-988cb9e41a8f"
                }],
                "count": 2,
                "timestamp": 1464677126509,
                "resultCode": "OK"
            }


            
## POST /order/list

### Get a list of orders

##### Request Definition

| Fields        | Description| Example
| ------------- |-------------|---------
|nonce    | Ever increasing integer |
|activeOnly      | true if order is active (only support true) |
|offset  | offset index (optional) | e.g. 0
|max | max number of orders to retrieved (optional)  | e.g. 10

Do not set offset and max for all orders


##### Response Definition

| Fields        | Description|  Possible values
| ------------- |-------------| ---------
| timestamp   | UNIX timestamp in milliseconds |
| resultCode | see result code| 
| orders| list of orders (see Order) | 
| count | number of orders returned 


##### Order

| Fields        | Description|  Possible values
| ------------- |-------------| ---------
| orderId  | Unique id of this order. | 
| timestamp  | unix timestamp | 
| orderType  | IMMEDIATE_OR_CANCEL, LIMIT, MARKET|
| orderStatus  | Status code of this order | ACTIVE
| settlementCurrency  | Settlement currency | All fiat (HKD, USD, etc) or Crypto (BTC)
| settlementCurrencyAmount  | Settlement currency amount | null / numeric 
| settlementCurrencyAmountOutstanding  | Settlement currency amount outstanding| null / numeric 
| tradedCurrency  | Traded currency | BTC, LTC, DOGE, XRP and STR etc
| tradedCurrencyAmount  | Traded currency amount | null / numeric
| tradedCurrencyAmountOutstanding  | Traded currency amount outstanding | null / numeric
| buyTradedCurrency  | buying traded currency or settlement currency | true or false
| trades  | the list of Trade | 
| replaceExistingOrderId  | The order id that this order replaced | 
| limitPriceInSettlementCurrency  | price in settlement currency, do not specify this when placing a market order  | 



+ Response 200 (application/json)

    + Body
    
            {
                "timestamp": 1464677126509,
                "resultCode": "OK"
            }
            
## POST /trade/list

### Get  trade history list of fill trades

##### Request Definition

| Fields        | Description| Example
| ------------- |-------------|---------
|nonce    | Ever increasing integer |
|offset  | offset index | e.g. 0
|max | max number of trades to retrieved  | e.g. 10

##### Response Definition

| Fields        | Description|  Possible values
| ------------- |-------------| ---------
| resultCode | see result code| 
| timestamp | unix timestamp | 
| trades| list of trade (see Trade) | 
| count | number of trades returned 


##### Trade

| Fields        | Description|  Possible values
| ------------- |-------------| ---------
| tradeId | trade id
| timestamp | unix timestamp | 
| orderId | order id (uuid )
| tradedCurrencyFillAmount | fill amount
| settlementCurrencyFillAmount | fill amount
| settlementCurrencyFillAmountUnrounded | fill amount
| price | price
| ccyPair | trade pair | e.g. BTCJPY


+ Response 200 (application/json)

    + Body
    
            {
                "timestamp": 1464677126509,
                "resultCode": "OK"
            }
            
            
# Group Funds
## POST /send
### Send Crypto Coin
<br>This services allow support crypto send operations. The API Key must have "move funds" authority, which is configured on the web site.
<br>Send bitcoin/altcoin to a crypto-currency address.

<br>Please note that a confirmation email would be sent to you to confirm this withdrawal. 
<br>If you do not click the confirmation link on the email, the withdrawal will be reversed after 10 minutes. 
<br>If you would like this feature disabled on your account, you can visit our site and create a Fiat Express Withdrawal setting. 
<br>Fiat Express Withdrawal allows you to perform withdrawal without the need of 2-factor authentication or response to our email confirmation as soon as the total value of the transactions is smaller than the daily limit you defined. 
<br>The transactions are evaluated against your favourite settlement currency available in our site.
<br>Should you have any questions, please contact service@bct.host.

##### Request Definition

| Fields        | Description| Example
| ------------- |-------------|---------
| nonce         | Ever increasing integer |
| ccy        | currency (e.g. BTC, LTC, XRP) |
| address  | valid address in the selected ccy |
| otp      | otp key for security reason |
| amount      | amount to send (must be less than the available balance) |
| destinationTag| (This parameter only use for crypto currency with distinationTag such as Ripple)Destination tag facilitate identifying the purpose of payments and allow a single address to be utilized by multiple users. Additionally, these tags enable the return of payments. | 


##### Response Definition

| Fields        | Description|  Example
| ------------- |-------------| ---------
| timestamp   | UNIX timestamp in milliseconds |
| resultCode   | Result code reflecting the success status of the operation. |
| transactionId       | internal transaction id of the transaction. *Note this is note the Bitcoin/crypto coin txid*. At the time this method is invoked, the blockchain TXID is not available. This identifier, however, can be used to match up the transaction updates send through the push data services. |


+ Request (application/json)

    + Headers
    
            Rest-Key: <Your-Rest-Key>
            Rest-Sign: <Your-Rest-Sign>
            
    + Body
    
            {
                "nonce":"1393225933584",
                "ccy":"BTC",
                "amount":"0.7653",
                "otp":"145212",
                "address":"113JFFCTt7MtqLi8BFS9TGqcxHqLqqttCH"
            }

+ Response 200 (application/json)

    + Body
    
            {
                "resultCode":"OK",
                "timestamp":1393320170292,
                "transactionId":"81400064-a048-48d4-8f56-47a1484a5222"
            }

## POST /receive
### Obtain a current receive address for the given token
Use this service to obtain a valid address to recieve crypto funds.

##### Request Definition

| Fields        | Description| Example
| ------------- |-------------|---------
| nonce         | Ever increasing integer |
| ccy         | traded currency | e.g. BTC, LTC, ETH, XRP, BCH |
| subAccount | Optional. Uuid of the subAccount of which you want to get coin address. If not specified, this will be your default subAccount.|

##### Response Definition

| Fields        | Description|  Example
| ------------- |-------------| ---------
| resultCode   | Result code reflecting the success status of the operation. |
| timestamp   | UNIX timestamp in milliseconds |
| address       | Valid crypto address | e.g. BTC, LTC, ETH, XRP, BCH |
| subAccount        | UUID of the subAccount of which the coin address is tied to |


+ Request (application/json)

    + Headers
    
            Rest-Key: <Your-Rest-Key>
            Rest-Sign: <Your-Rest-Sign>
        
    + Body
        
            {
                "nonce":"1393225933584",
                "ccy":"DOGE"
            }

+ Response 200 (application/json)

    + Body
    
            {
               "address": "18PW33D6ci3VQNTDmuQLV8mo9embZ5jKW3",
               "resultCode": "OK",
               "subAccount": "550a1ae8-3867-4557-b40c-1a0434a65f95",
               "timestamp": 1401332352873
            }

## POST /receive/create
### Create a new receive address for the given token
Use this service to create a new address to recieve crypto funds.  New address will be created only the specified sub-account has received at least one account. Note that each account has a max number of sub-accounts, contact support to increase this limit.

##### Request Definition

| Fields        | Description| Example
| ------------- |-------------|---------
| nonce         | Ever increasing integer |
| ccy         | traded currency | e.g. BTC, LTC, ETH, XRP, BCH |
| subAccount | Optional. Uuid of subAccount for which you want to create a new coin address. If not specified, this will be your default subAccount. |

##### Response Definition

| Fields        | Description|  Example
| ------------- |-------------| ---------
| resultCode   | Result code reflecting the success status of the operation. |
| timestamp   | UNIX timestamp in milliseconds |
| address       | Valid new crypto address | e.g. BTC, LTC, ETH, XRP, BCH  |
| subAccount    | UUID of the sub account that the coin address is tied to.  |

+ Request (application/json)

    + Headers
    
            Rest-Key: <Your-Rest-Key>
            Rest-Sign: <Your-Rest-Sign>
        
    + Body
    
            {
                "nonce":"1393225933579",
                "ccy":"DOGE"
            }

+ Response 200 (application/json)

    + Body
    
            {
               "address": "1NM2Jjy8sL6gKQx2uTmdzQpSxtRq8oKMT5",
               "resultCode": "OK",
               "subAccount": "550a1ae8-3867-4557-b40c-1a0434a65f95",
               "timestamp": 1401333876577
            }


## POST /transferfunds
### Move funds inbetween platform accounts 
Use this service to move funds inbetween different accounts that allows for trading.

##### Request Definition

| Fields        | Description| Example
| ------------- |-------------|---------
| nonce         | Ever increasing integer |
| from          | This is the move "From" account. Must be in CAPS |e.g. `AVAILABLE`, `EXCHANGE`  |
| to            | This is the move "To" account. Must be in CAPS | e.g. `EXCHANGE`, `AVAILABLE`  |
| amount        | This is the amount to move |
| ccy           | Currency selected to move currency | e.g. BTC, ETH, LTC, BCH, XRP, USD, AUD |

##### Response Definition

| Fields        | Description|  Example
| ------------- |-------------| ---------
| timestamp     | UNIX timestamp in milliseconds |
| UUID          | Returns the transfer fund transaction uuid |
| status        | If transfer fund is successful, “OK” is returned |
| resultCode    | Result code reflecting the success status of the operation. `INVALID_PARAMETERS` - Too many decimals or Exchange product not available`INSUFFICIENT_BALANCE` - account has insufficient funds to move|

+ Request (application/json)

    + Headers
    
            Rest-Key: <Your-Rest-Key>
            Rest-Sign: <Your-Rest-Sign>
        
    + Body
        
            {
                "nonce":"${nonce}",
                "from":"EXCHANGE",
                "to":"AVAILABLE",
                "amount":"5.23",
                "ccy":"USD"
            }

+ Response 200 (application/json)

    + Body
    
            {
              "uuid": "6a121bf0-6866-4a36-9244-81d155b62f21",
              "status": "OK"
            }
            
            // Wrong from/to, or too many decimal places
            // call when the platform does not support the EXCHANGE balance
            {
              "timestamp": "1575602536706",
              "resultCode": "INVALID_PARAMETERS"
            }
            
            // Account has insufficient balance
            {
              "timestamp": "1575602536706",
              "resultCode": "INSUFFICIENT_AVAILABLE_BALANCE"
            }

  
# Group Trading
## POST /order/new
### Create/Replace an order

By using this method, you can create an order with different order type. In addition, you can replace an existing order by providing additional parameters

* tradedCurrencyAmount and settlementCurrencyAmount is mutually exclusive. You can only specify one

##### Request Definition (Create new order)

| Fields        | Description| Example
| ------------- |-------------|---------
| nonce    | Ever increasing integer |
| tonce    | Ever increasing integer |
| order | see Order |

###### Order

| Fields        | Description| Example
| ------------- |-------------|---------
| orderType  | Order type | LIMIT / MARKET |
| tradedCurrency  | Traded currency | BTC, LTC, DOGE, XRP and STR etc|
| tradedCurrencyAmount  | traded currency amount, numeric number with at most 8 decimal places | 1234.12345678|
| settlementCurrency  | Settlement currency | All fiat (HKD, USD, etc) or Crypto (BTC)
| settlementCurrencyAmount  | settlement currency amount, numeric number with at most 8 decimal places | 1234.12345678|
| buyTradedCurrency  | buying traded currency or settlement currency | true or false
| limitPriceInSettlementCurrency  | price in settlement currency, do not specify this when placing a market order  | 3000.12345
| immediateOrCancel | must be true for IMMEDIATE_OR_CANCEL orders. If false or not provided while order type is IMMEDIATE_OR_CANCEL, it would behave like LIMIT order. If set to true while order type is LIMIT/IMMEDIATE_OR_CANCEL, it would behave like IMMEDIATE_OR_CANCEL order. | true or false
| hiddenOrder | |
| fillOrKill | |
| replaceExistingOrderUuid | to replace existing order |
| replaceOnlyIfActive | Replace the order only if the order being replace is active |

##### Response Definition

| Fields        | Description|  Example
| ------------- |-------------| ---------
| orderId       | Unique id of this order. |
| timestamp     | UNIX timestamp in milliseconds |
| resultCode    | Result code reflecting the success status of the operation. | 
| orderState    | Current order state | Including ACTIVE / PARTIAL_FILL / FULL_FILL / EXPIRED / PENDING_SUBMISSION. If order state is PENDING_SUBMISSION, it indicates that order is in doubtful state.  Need to do order enquiry to confirm the latest state.  | 

##### Possible Result code 

| Result Code      | Description
| ------------- |-------------
| ORDER_REQUEST_SUBMITTED       | Order request submitted. It is generally considered a successful response.
| INSUFFICIENT_AVAILABLE_BALANCE   | Insufficient available balance
| TOO_MANY_OPEN_ORDERS   | Too many open orders
| TOO_SMALL | Order value too small
| USER_NOT_VERIFIED | User is not verified for trading |
| INVALID_PARAMETERS  | Invalid parameters, including wrong currency pair, order amount/rate too big, too many decimal place, etc

+ Request (application/json)

    + Headers
    
            Rest-Key: <Your-Rest-Key>
            Rest-Sign: <Your-Rest-Sign>
        
    + Body
    
            {
                "order": {
                    "orderType": "LIMIT",
                    "buyTradedCurrency": true,
                    "tradedCurrency": "BTC",
                    "settlementCurrency": "HKD",
                    "tradedCurrencyAmount": "1.01",
                    "limitPriceInSettlementCurrency": "3000"
                },
                "tonce": 1403076674170000
            }

+ Response 200 (application/json)

    + Body
    
            {
                "orderId": "eb7ebd89-0593-415e-b96b-d4d86cf35bb6",
                "timestamp": 1403076674228,
                "resultCode": "ORDER_REQUEST_SUBMITTED"
            }



## POST /order/info
### Getting Order status

* This method return order info of filled or active status.

##### Request Definition

| Fields        | Description| Example
| ------------- |-------------|---------
| nonce    | Ever increasing integer |
| tonce    | Ever increasing integer |
| orderId  | Unique id of this order. | "565f2cdf-3f34-4881-bc80-46584c2c6b8d"

##### Response Definition

| Fields        | Description|  Possible values
| ------------- |-------------| ---------
| resultCode | see result code| 
| timestamp   | UNIX timestamp in milliseconds |
| order| see Order |


##### Order

| Fields        | Description|  Possible values
| ------------- |-------------| ---------
| orderId  | Unique id of this order. | 
| timestamp  | unix timestamp | 
| orderType  | LIMIT, MARKET|
| orderStatus  | Status code of this order | ACTIVE
| settlementCurrency  | Settlement currency | All fiat (HKD, USD, etc) or Crypto (BTC)
| settlementCurrencyAmount  | Settlement currency amount | null / numeric 
| settlementCurrencyAmountOutstanding  | Settlement currency amount outstanding| null / numeric 
| tradedCurrency  | Traded currency | BTC, LTC, DOGE, XRP and STR etc
| tradedCurrencyAmount  | Traded currency amount | null / numeric
| tradedCurrencyAmountOutstanding  | Traded currency amount outstanding | null / numeric
| buyTradedCurrency  | buying traded currency or settlement currency | true or false
| trades  | the list of Trade | 
| immediateOrCancel | true for IMMEDIATE_OR_CANCEL order. orderType should be LIMIT | true or false
| replaceExistingOrderId  | The order id that this order replaced | 
| limitPriceInSettlementCurrency  | price in settlement currency, do not specify this when placing a market order  | 


##### Trade

| Result Code      | Description
| ------------- |-------------
| tradeId | trade id
| orderId | order id 
| timestamp | unix timestamp | 
| tradedCurrencyFillAmount | fill amount
| settlementCurrencyFillAmount | fill amount
| settlementCurrencyFillAmountUnrounded | fill amount
| price | price
| ccyPair | trade pair | e.g. BTCJPY
| side | BUY or SELL |

##### Possible result code

| Result Code      | Description
| ------------- |-------------
| ORDER_NOT_FOUND | Order not found

##### Possible order status code

| Status Code      | Description
| ------------- |-------------
| PENDING_SUBMISSION      |  Pending to be processed by the system
| ACTIVE   | Active. Pending to be matched by the system
| EXPIRED   | Expired
| PARTIAL_FILL | Partially filled
| FULL_FILL  | Full filled
| NO_FILL  | Not filled


+ Request (application/json)

    + Headers
    
            Rest-Key: <Your-Rest-Key>
            Rest-Sign: <Your-Rest-Sign>
        
    + Body
    
            {
                "orderId": "565f2cdf-3f34-4881-bc80-46584c2c6b8d",
                "tonce": 1403076677349000
            }

+ Response 200 (application/json)

    + Body

            {
                "order": {
                    "buyTradedCurrency": true,
                    "executedAverageRate": null,
                    "limitPriceInSettlementCurrency": "3000.00000",
                    "orderId": "565f2cdf-3f34-4881-bc80-46584c2c6b8d",
                    "orderStatus": "ACTIVE",
                    "orderType": "LIMIT",
                    "replaceExistingOrderId": "eb7ebd89-0593-415e-b96b-d4d86cf35bb6",
                    "settlementCurrency": "HKD",
                    "settlementCurrencyAmount": null,
                    "settlementCurrencyAmountOutstanding": null,
                    "timestamp": 1403076674000,
                    "tradedCurrency": "BTC",
                    "tradedCurrencyAmount": "2.01",
                    "tradedCurrencyAmountOutstanding": "2.01",
                    "trades": []
                },
                "resultCode": "OK",
                "timestamp": 1403076677368
            }  
            
## POST /order/{orderId}

### Getting Order Info By Order ID

Get order info by order Id whatever its status.

##### Request Definition

| Fields        | Description| Example
| ------------- |-------------|---------
| nonce    | Ever increasing integer |


##### Response Definition

| Fields        | Description|  Possible values
| ------------- |-------------| ---------
| resultCode | see result code| 
| timestamp   | UNIX timestamp in milliseconds |
| order| see Order |


##### Order

| Fields        | Description|  Possible values
| ------------- |-------------| ---------
| orderId  | Unique id of this order. | 
| timestamp  | unix timestamp | 
| orderType  | LIMIT, MARKET|
| orderStatus  | Status code of this order | ACTIVE
| settlementCurrency  | Settlement currency | All fiat (HKD, USD, etc) or Crypto (BTC)
| settlementCurrencyAmount  | Settlement currency amount | null / numeric 
| settlementCurrencyAmountOutstanding  | Settlement currency amount outstanding| null / numeric 
| tradedCurrency  | Traded currency | BTC, LTC, DOGE, XRP and STR etc
| tradedCurrencyAmount  | Traded currency amount | null / numeric
| tradedCurrencyAmountOutstanding  | Traded currency amount outstanding | null / numeric
| buyTradedCurrency  | buying traded currency or settlement currency | true or false
| replaceExistingOrderId  | The order id that this order replaced | 
| immediateOrCancel | true for IMMEDIATE_OR_CANCEL order. orderType should be LIMIT | true or false
| limitPriceInSettlementCurrency  | price in settlement currency, do not specify this when placing a market order  | 
| trades  | the list of Trade | 

##### Trade

| Result Code      | Description
| ------------- |-------------
| tradeId | trade id
| orderId | order id 
| timestamp | unix timestamp | 
| tradedCurrencyFillAmount | fill amount
| settlementCurrencyFillAmount | fill amount
| settlementCurrencyFillAmountUnrounded | fill amount
| price | price
| ccyPair | trade pair | e.g. BTCJPY
| side | BUY or SELL |

##### Possible result code

| Result Code      | Description
| ------------- |-------------
| ORDER_NOT_FOUND | Order not found

##### Possible order status code

| Status Code      | Description
| ------------- |-------------
| PENDING_SUBMISSION      |  Pending to be processed by the system
| ACTIVE   | Active. Pending to be matched by the system
| EXPIRED   | Expired
| PARTIAL_FILL | Partially filled
| FULL_FILL  | Full filled
| NO_FILL  | Not filled
| REPLACED | Amended order
| REPLACED_PARTIAL | partially amended order
| USER_CANCEL | Cancelled order
| USER_CANCEL_PARTIAL | partially cancelled order
| SUSPENDED | suspended order

+ Parameters
    + orderId - orderId which required to get
    
+ Request (application/json)

    + Headers
    
            Rest-Key: <Your-Rest-Key>
            Rest-Sign: <Your-Rest-Sign>
        
    + Body
    
            {
                "nonce": 1403076677349000
            }

+ Response 200 (application/json)

    + Body

            {
                "order": {
                    "orderType": "LIMIT",
                    "tradedCurrency": "BTC",
                    "settlementCurrency": "USD",
                    "tradedCurrencyAmount": "0.09000000",
                    "buyTradedCurrency": false,
                    "limitPriceInSettlementCurrency": "20000.00000",
                    "timestamp": "1571278303580",
                    "orderId": "86854158",
                    "tradedCurrencyAmountOutstanding": "0.09000000",
                    "orderStatus": "ACTIVE",
                    "trades": []
                },
                "timestamp": "1571278359566",
                "resultCode": "OK"
            }
            
## POST /order/cancel

### Cancel a list of orders

##### Request Definition

| Fields        | Description| Example
| ------------- |-------------|---------
| nonce    | Ever increasing integer |
| orderIds  | list of order ids  | e.g. order id : "565f2cdf-3f34-4881-bc80-46584c2c6b8d"

##### Response Definition

| Fields        | Description|  Example
| ------------- |-------------| ---------
| timestamp   | UNIX timestamp in milliseconds |
| resultCode | see result code| 
| resultCodeList| list of Cancel Status |

##### Cancel Status

| Fields        | Description|  Example
| ------------- |-------------| ---------
| uuid   | order's uuid |
| errorCode | error code | 

##### Error Code

| Fields        | Description|  
| ------------- |-------------|
| ORDER_NOT_FOUND   | can not found corresponding order
| CANCEL_REQUEST_SUBMITTED | cancel request submiited
| ORDER_CANCEL_WRONG_STATE | order cannot be cancel 

+ Response 200 (application/json)

    + Body

            {
                "resultCode": "OK",
                "timestamp": 1403076677368
            }  
            
            
# Group Retail Trading

## POST /retail/quote
This endpoint allows quote the price of currency pair

##### Request Definition

| Fields        | Description   | Example 
| ------------- |---------------|---------
| nonce    | Ever increasing integer |
| quoteRequest | see Quote Request |


##### Quote Request

| Fields        | Description   | Example 
| ------------- |---------------|---------
|tradedCurrency | traded currency
|settlementCurrency | settlement currency
|tradedCurrencyAmount | traded currency amount
|settlementCurrencyAmount | settlement currency amount
|buyTradedCurrency | true for buy currency | false for sell
|isIndicativeQuote | for for retail quote
|customRef | customer reference in uuid format


##### Response Definition

| Fields        | Description   | Example
| ------------- |---------------|---------
|resultCode | result Code
|timestamp | unix timestamp | 
|quoteResponse | see Quote Response


##### Quote Response

| Fields        | Description   | Example
| ------------- |---------------|---------
| responseCode | see QuoteResponseCode
| buyTradedCurrency | true for buy  or false for sell
| tradedCurrency| tradedCurrency currency | e.g. BTC
| settlementCurrency | settlement currency | e.g. USD
| quotedSettlementCurrencyAmount | quoted settlement currency amount
| quotedTradedCurrencyAmount | quoted traded currency amount
|quotedAmountToDeliver | quoted amount to deliver
|wholesaleRateInSettlementCurrency | wholesale rate in settlement currency
|retailRateInSettlementCurrency | retail rate in settlement currency
|customRef | custom refernece 
|quoteId | quote id
|quoteExpiresAt | timestamp which the quote is expired at
|quoteCreatedAt | timestamp which the quote is created at
|maxAmount | max amount

+ Response 200(application/json)

    + Body
    
            {
               "resultCode": "OK",
               "exists": true
            }
            
            
## POST /retail/trade
This endpoint to trade order previously quote

##### Request Definition

| Fields        | Description   | Example 
| ------------- |---------------|---------
| nonce    | Ever increasing integer |
| tradeRequest | see Trade Request |


##### Trade Request

| Fields        | Description   | Example 
| ------------- |---------------|---------
| quoteId | quote Id 
| customRef | custom refernece  
| amount | amount in traded currency


##### Response Definition

| Fields        | Description   | Example
| ------------- |---------------|---------
|resultCode | result Code
| timestamp | unix timestamp | 
|tradeResponse | see Trade Response


##### Trade Response

| Fields        | Description   | Example
| ------------- |---------------|---------
| responseCode | see Trade Response Code
| tradeId | trade id
| quoteId| quote Id

##### Trade Response Code

| Fields        | Description   | 
| ------------- |---------------|
| INVALID_QUOTE_ID
| QUOTE_EXPIRED
| EXECUTED
| INSUFFICIENT_FUND
| ENGINE_NOT_AVAILABLE
| INSUFFICIENT_LIQUIDITY
| DISCOUNT_CODE_NOT_VALID,DAILY_LIMIT_EXCEEDED
| PENDING_EXECUTE
| MERCHANT_NOT_AVAILABLE

+ Response 200(application/json)

    + Body
    
            {
               "resultCode": "OK",
               "exists": true
            }
            
            
# Group Streaming

Streaming is based on socket.io, and does not support pure websockets (it is long polling).
Java or other language socket.io clients may work if they support long polling.

## Public Events

## Market Tick Event /public/tick/{market}/{ccyPair}
Get market ticks for a specific market and currency pair

### Subscription

| Fields        | Description| Example
| ------------- |-------------|---------
| market         | exchange market | BCT
| ccyPair        | currency pair |  BTCUSD (or any other supported currency pair, BTC as traded currency, USD as settlement currency)

### Event Definition

| Fields        | Description|  Example
| ------------- |-------------| ---------
| event       | event type | marketTick
| data       | see Market Tick | 


### Market Tick

| Fields        | Description|  Example
| ------------- |-------------| ---------
| market   | exchange market | BCT
| timestampMillis   | unix timestamp in millisecond | 1399711469626 in below example, which is equivalent to Sat, 10 May 2014 08:44:29 GMT
| bid   | best bid price | 551.16362 USD/BTC in below example
| ask   | best ask price| 584.28841 USD/BTC in below example
| volume   | traded volume in settlement currency in the past 24 hours | 2.25661368 USD
| vwap   | volume weighted average price of trades in the  past 24 hours | 567.88653298 USD/BTC
| high   | highest price of trades in the past 24 hours | 580.519619 USD/BTC
| low   | lowest price of trades in the past 24 hours | 554.718747 USD/BTC
| ccyPair   | currency pair | BTCUSD 
| last   | price of latest trade as of data.timestampMillis | 554.718747 USD/BTC



### Example JSON 

```javascript
    {
      "event": "marketTick",
      "data": [
        {
          "market": "BCT",
          "timestampMillis": 1399711469626,
          "bid": 551.16362,
          "ask": 584.28841,
          "volume": 2.25661368,
          "vwap": 567.88653298,
          "high": 580.519619,
          "low": 554.718747,
          "ccyPair": "BTCUSD",
          "last": 554.718747
        }
      ]
    }
```

## Order Book Update   public/orderBook/{market}/{ccyPair}
Get order book for a specific market and currency pair

### Subscription

| Fields        | Description| Example
| ------------- |-------------|---------
| market         | BCT |
| ccyPair        | currency pair | BTCUSD (or any other supported currency pair, BTC as traded currency, USD as settlement currency)

### Event Definition

| Fields        | Description|  Example
| ------------- |-------------| ---------
| event       | event type | orderBook
| data | order book

### Order Book
| Fields        | Description|  Example
| ------------- |-------------| ---------
| market   |  BCT | BCT
| ccyPair   | currency pair | BTCUSD 
| timestampMillis   | unix timestamp in millisecond | 1399713934547
| bids | all bid orders. See Order |
| asks | all ask orders. See Order |

### Order

| Fields        | Description|  Example
| ------------- |-------------| ---------
| price   | price of  orders; best order(s) (with highest price) is(/are) on top of the book | 551.16362 USD/BTC 
| quantity   | aggregated quantity of orders at the specific price | 1.48308644 BTC 
| total   | price*(aggregated )quantity of orders at the specific price | 817.42 USD

### Example JSON

```javascript
    {
       "event": "orderBook",
       "data": [
          {
             "market": "BCT",
             "ccyPair": "BTCUSD",
             "timestampMillis": "1399713934547",
             "bids": [
                {
                   "price": 551.16362,
                   "quantity": 1.48308644,
                   "total": 817.42
                },
                {
                   "price": 512.71035,
                   "quantity": 220.2827068,
                   "total": 112941.22
                },
                {
                   "price": 102.54207,
                   "quantity": 6.16855199,
                   "total": 632.53
                },
                {
                   "price": 102.53957,
                   "quantity": 0.1,
                   "total": 10.25
                },
                {
                   "price": 101,
                   "quantity": 0.1,
                   "total": 10.1
                },
                {
                   "price": 100,
                   "quantity": 0.1,
                   "total": 10
                },
                {
                   "price": 76.90655,
                   "quantity": 0.01666672,
                   "total": 1.28178
                },
                {
                   "price": 64.08879,
                   "quantity": 4,
                   "total": 256.35
                },
                {
                   "price": 51.27103,
                   "quantity": 2,
                   "total": 102.54
                },
                {
                   "price": 46.18652,
                   "quantity": 1.9,
                   "total": 87.75
                },
                {
                   "price": 44.59388,
                   "quantity": 1.8,
                   "total": 80.26
                },
                {
                   "price": 38.45328,
                   "quantity": 1.5,
                   "total": 57.67
                },
                {
                   "price": 10,
                   "quantity": 0.1,
                   "total": 1
                }
             ],
             "asks": [
                {
                   "price": 584.28841,
                   "quantity": 3.31955977,
                   "total": 1939.58
                },
                {
                   "price": 597.27259,
                   "quantity": 11,
                   "total": 6569.99
                },
                {
                   "price": 610.25678,
                   "quantity": 2,
                   "total": 1220.51
                },
                {
                   "price": 616.74887,
                   "quantity": 0.01,
                   "total": 6.16
                },
                {
                   "price": 623.24097,
                   "quantity": 23,
                   "total": 14334.54
                },
                {
                   "price": 636.22515,
                   "quantity": 2,
                   "total": 1272.45
                },
                {
                   "price": 649.2095,
                   "quantity": 0.995,
                   "total": 645.96
                },
                {
                   "price": 650.52074,
                   "quantity": 1,
                   "total": 650.52
                },
                {
                   "price": 813.15093,
                   "quantity": 4,
                   "total": 3252.6
                },
                {
                   "price": 5193674727.42297,
                   "quantity": 0,
                   "total": 12.98419
                }
             ]
          }
       ]
    }
```


## Exchange Trades   public/trades/{market}/{ccyPair}
Get trade updates for a specific market(exchange) and currency pair

### Subscription

| Fields        | Description| Example
| ------------- |-------------|---------
| market         | exchange market  BCT
| ccyPair        | currency pair | BTCUSD (or any other supported currency pair, BTC as traded currency, USD as settlement currency)

### Event Definition

| Fields        | Description|  Example
| ------------- |-------------| ---------
| event      | event type | exchangeTrade
| data      | see Exchange Trade | 

### Exchange Trade

| Fields        | Description|  Example
| ------------- |-------------| ---------
| uuid   |  Universally Unique IDentifier of the reported trade | 2d5df61a-3a77-46ee-8b8e-457a20f39b74USD 
| primary   | false if this trade is not primarily traded in {ccyPair}, true otherwise | false 
| tradedAmount   | amount of traded currency in this trade | 0.1 BTC
| settlementAmount   | amount of settlement currency in this trade | 55.250435 USD
| tradedCcy   | traded currency (currently it can be one of BTC, LTC, XRP and STR)| BTC 
| settlementCcy   | settlement currency (currently it can one of any supported FIAT currency, BTC, and LTC | USD 
| ccyPair   | currency pair, it should be the same as specified {ccyPair} | BTCUSD i
| price   | price of this trade | 552.50435 USD/BTC in below example
| side   | usually this is the side of incoming order | SELL
| timestampMillis   | unix timestamp in millisecond, time when this trade happens | 1399711468899 
| version   | 
| market   | market(exchange), it should be the same as specified {market} | BCT 

### Example JSON

```javascript
    {
      "event": "exchangeTrade",
      "data": [
        {
          "uuid": "2d5df61a-3a77-46ee-8b8e-457a20f39b74USD",
          "primary": false,
          "tradedAmount": 0.1,
          "settlementAmount": 55.250435,
          "tradedCcy": "BTC",
          "settlementCcy": "USD",
          "ccyPair": "BTCUSD",
          "price": 552.50435,
          "side": "SELL",
          "timestampMillis": 1399711468899,
          "version": 0,
          "market": "BCT"
        }
      ]
    }
```

## Private Events /private/{uuid}

Events specific to the logged in user.

This single topic subscription returns:

* Account balances updates
* Order status updates
* Order fills
* Activity events (notifications such authentication failures, order fill etc)

All private events have the "event" fields, this should be used to determine the type of event.

### Subscription

| Fields        | Description | Example
| ------------- |-------------|---------
| uuid | uuid which is used to access user-specific data from the push services. This may change with each new push token so do not store it for re-use (this is provided by a request to dataToken) | 

## Account balance update

Changes fairly requently - such as available balance changes when an order is placed.

### Event Definition

| Fields        | Description|  Example
| ------------- |-------------| ---------
| event       | event type | "account"
| data | see Account|


### Account

| Fields        | Description|  Example
| ------------- |-------------| ---------
| balance   | total balance of {data.ccy} for this account | 
| availableBalance | available balance of {data.ccy} for this account
| timestampMillis | unix timestamp in millisecond
| user | user's uuid
| uuid | this account's uuid

### Example JSON


```javascript
    {
      "event": "account",
      "data": [
        {
          "balance": "4032.07",
          "availableBalance": "4032.07",
          "ccy": "CNY",
          "timestampMillis": "1399711469461",
          "user": "f51156d2-8416-11e3-ab68-525400098064",
          "uuid": "f5148924-8416-11e3-ab68-525400098064"
        }
      ]
    }
```

## Order status updates

Order states as the order moves through the state machine (lifecycle).

### Event Definition

| Fields        | Description|  Example
| ------------- |-------------| ---------
| event       | event type | order
| data | order. See Order| 



### Order
| Fields        | Description|  Example
| ------------- |-------------| ---------
| uuid   | order's uuid
| orderState | state of this order. See Order State
| rate | quoted price of this order in {settlementCcy per tradeCcy}
| orderDateTime | time of creation of this order, denoted by unix timestamp in millisecond
| settlementCcy | settlement currency (currently it can be any supported FIAT currency, BTC, and LTC)
| tradedCcy | traded currency (currently it can be any one of BTC, LTC, DOGE, XRP and STR)
| side | BUY if this is a bid order (buy traded ccy), SELL if this is an ask order (sell traded ccy)
| tradedCcyTotalEstimate | fixed amount either in traded currency or in settelment currency. This is the same as {tradedAmount} if user specified fixed amount is in {tradeCcy}; or it is calculated by {fixedAmount} divided by {user specified limit price (rate)} and then round to feasible decimal places
| tradedAmount | total amount of traded currency
| tradedAmountOutstanding | amount of traded currency outstanding (not filled)
| user | user uuid which this order is belong to

### Order State

Enumeration of all order states possible

| State | Description
| ----- | ----------
| DRAFT | this order is newly created
| PENDING_SUBMISSION | this order is about to be active
| ACTIVE | this order is active
| EXPIRED | this order is expired
| PARTIAL_FILL | this order is partially filled
| FULL_FILL | this order is fully filled
| NO_FILL | mainly for Market order or Immediate Or Cancel order, this order is closed without any fills
| CANCEL_UNFUNDED | this order is cancelled due to the user's account doesn't have enough traded currency or settlement currency to fund this trade 
| USER_CANCEL | this order is canceled by user
| CANCELLED | this order is canceled
| SUSPENDED | this order is suspended
| USER_CANCEL_PARTIAL | this order is cancelled by user; and before the order was cancelled, it was partially filled
| CANCEL_TOO_SMALL | this order is cancelled when it's outstanding amount is below tradable minimum amount
| REPLACED | this order is replaced by another order 
| REPLACED_PARTIAL | this order is replaced by another order; and before the order was replaced, it was partially filled
| CANCELLED_REPLACE_FAILED | this order is not successfully replaced, due to replaceOnlyIfActive flag is set to true and the order is not active when replacing

### Example JSON

```javascript
    {
      "event": "order",
      "data": [
        {
          "uuid": "aa171fcc-3616-46ef-a722-cc0798d5e727",
          "orderState": "FULL_FILL",
          "rate": 3433.06521,
          "orderDateTime": 1399711468000,
          "settlementCcy": "CNY",
          "tradedCcy": "BTC",
          "side": "SELL",
          "tradedCcyTotalEstimate": 0.1,
          "tradedAmount": 0.1,
          "tradedAmountOutstanding": 0,
          "user": "f51156d2-8416-11e3-ab68-525400098064"
        }
      ]
    }
```

## Order fill transactions

A trade (fill transaction) occurred.

### Event Definition

Order states as the order moves through the state machine (lifecycle).

| Fields        | Description|  Example
| ------------- |-------------| ---------
| event       | event type | trade
| data | Trade data |

### Trade

| Fields        | Description|  Example
| ------------- |-------------| ---------
| uuid   | a Universally Unique IDentifier of this fill transaction (trade)
| order | to which parent order this fill transaction belongs, identified by the order's uuid (different from {uuid})
| tradedCcy | traded currency (currently it can be any one of BTC, LTC, DOGE, XRP and STR)
| settlementCcy | settlement currency (currently it can be any supported FIAT currency, BTC, and LTC)
| tradedAmount | amount of traded currency in this fill transaction
| settlementAmount | amount of settlement currency in this fill transaction
| side | BUY if this fill transaction belongs to a bid order (buy traded ccy), SELL if this fill transaction belongs to an ask order (sell traded ccy)
| price | price at which this fill transaction happens, denoted in {settlementCcy per tradeCcy}
| timestampMillis | unix timestamp in millisecond, time as of which this fill transaction happens
| orderOutstandingFixedAmount | amount outstanding unfilled out of total fixed amount of the parent order
| orderTotalFixedAmount | total fixed amount of the parent order 
| orderFixedAmountCcy | this indicates which currency the parent order's fixed amount is in
| orderTradedCcyExecutedAmount | executed amount in traded currency of the parent order as of {timestampMillis}
| orderSettlementCcyExecutedAmount | executed amount in settlement currency of the parent order as of {timestampMillis} 
| user | user's uuid

### Example JSON


```javascript
    {
      "event": "trade",
      "data": [
        {
          "uuid": "0a92baf5-6525-4e58-8def-afc929eb61b7",
          "order": "0558e23e-d143-4bc6-a354-0007887133cb",
          "tradedCcy": "BTC",
          "settlementCcy": "JPY",
          "tradedAmount": "0.01000000",
          "settlementAmount": "815.47",
          "side": "BUY",
          "price": "81546.52477",
          "timestampMillis": 1400208567305,
          "orderOutstandingFixedAmount": "0.00000000",
          "orderTotalFixedAmount": "0.01000000",
          "orderFixedAmountCcy": "BTC",
          "orderTradedCcyExecutedAmount": "0.01000000",
          "orderSettlementCcyExecutedAmount": "815.47",
          "user": "85c420e1-1f61-434f-a350-b5c294486cf1"
        }
      ]
    }
```
    
## Activity events

Many different types of user notifications are possible

### EventTypes:

|Event Types| Description |
|-----------|--------------|
| COIN_WITHDRAWAL| coin withdrawal
|   COIN_DEPOSIT| coin deposit
|    PASSWORD_CHANGE|
|    LOGIN|
|    LOGIN_FAILED|
|    ORDER_SUBMITTED|
|    ORDER_CANCELLED,
|    ORDER_FILLED|
|    ORDER_PARTIALLY_FILLED|
|    ORDER_COULD_NOT_FILL|
|    ORDER_CANCELLED_INSUFFICIENT_FUNDS|
|    ACCOUNT_LOCKED|
|    FIAT_WITHDRAWAL|
|    FIAT_DEPOSIT |
|    CASH_WITHDRAWAL|
|    CASH_DEPOSIT |
|    CASH_DEPOSIT_NOTIFICATION |
|    VERIFICATION_REQUEST|
|    USER_REGISTRATION|
|    USER_VERIFICATION|
|    VERIFY_TOO_MANY_TRIES|
|    TRANSACTION_REVERSAL|
|    DEPOSIT_NOTIFY_EXPIRE|
|    DEPOSIT_NOTIFY_SUBMITTED|
|    OTP_ENABLED|
|    OTP_DISABLED|
|    APIKEY_UPDATED|
|    APIKEY_PASSWORD_RESET|
|    APIKEY_CREATED|
|    COUPON_DEPOSIT|
|    CASH_DEPOSIT_SUSPENDED|
|    CASH_DEPOSIT_PENDING_FOR_FOUR_EYES|
|    PRICE_ALERT_NOTIFICATION|

### Example JSON

```javascript
    {
      "event": "userEvent",
      "data": [
        {
          "message": "Order has been filled",
          "eventType": "ORDER_FILLED",
          "user": "f51156d2-8416-11e3-ab68-525400098064",
          "ip": "",
          "timestampMillis": "1399713311966"
        }
      ]
    }
```
